spring:
  application:
    name: ESG-Backend
  # ?? dev ??
  profiles:
    active: dev
  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session ??
  session:
    # todo ????????? session????? Redis?
    # store-type: redis
    # 30 ???
    timeout: 2592000

  # ?????
  # todo ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ESG
    username: root
    password: ZbW55866

  mail:
    host: smtp.163.com
    username: pantianyu0827@163.com
    password: OETBZTXNTWTZYNCR
    port: 587
    protocol: smtp
    properties:
      "mail.smtp.ssl.enable": true
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true


#  redis:
#    host: localhost
#    port: 6379
#    password: your_redis_password
#    database: 0
#    timeout: 10000
#
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /

server:
  port: 8081
  servlet:
    context-path:
